### ISSUE TITLE
Style problems

### ISSUE THREAD

**Issue by andreaniris** [wdelfuego/nova-calendar#75] opened 2024-01-25 09:51 UTC
Hello! I installed nova-calendar on a new project and immediately noticed some display issues:
- The date picker arrow is not visible. However, it works: it's clickable and you can choose the month and year;
- The selected filters are barely visible in both light and dark mode.

I tried it on Chrome, Safari, and Firefox with the same results. I am using version 2.1.4. In another project, where I have version 2.1.2, it works normally and the display is fine.

https://github.com/wdelfuego/nova-calendar/assets/80703995/0ce34508-08e9-4050-a0f0-492487d4ba71

**Comment by Eli-Pez** [comment] 2024-02-27 10:59
Hello this is Eli-Pez (again me). Signed in with wrong account LOL. Anyway...

I updated to Nova 4.32.15. This is the actual html that does not work. 
```
<div id="nc-control">
    <div class="left-items"><a href="#" class="button hover:bg-gray-100 dark:hover:bg-gray-700" title="Alt + ←">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7m8 14l-7-7 7-7"></path>
            </svg>
        </a><a href="#" class="button hover:bg-gray-100 dark:hover:bg-gray-700" title="Alt + H">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="2" fill="currentColor"></circle>
            </svg>
        </a><a href="#" class="button hover:bg-gray-100 dark:hover:bg-gray-700" title="Alt + →">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7"></path>
            </svg>
        </a>
        <div dusk="month-picker"><span><dropdowntrigger class="toolbar-button px-2" id="nova-ui-dropdown-button-11"
                                                        aria-expanded="false" aria-haspopup="true"
                                                        aria-controls="nova-ui-dropdown-menu-12"
                                                        style="padding-left: 0px;"></dropdowntrigger></span></div>
        <h1 class="text-90 font-normal text-xl md:text-2xl noselect"><span>Febbraio '24</span></h1></div>
    <div class="center-items"></div>
    <div class="right-items">
        <div dusk="filter-selector"><span><dropdowntrigger
                    class="text-white hover:text-white dark:text-gray-800 dark:hover:text-gray-800 toolbar-button px-2"
                    id="nova-ui-dropdown-button-13" aria-expanded="false" aria-haspopup="true"
                    aria-controls="nova-ui-dropdown-menu-14"><svg xmlns="http://www.w3.org/2000/svg" fill="none"
                                                                  viewBox="0 0 24 24" stroke="currentColor" width="24"
                                                                  height="24" class="inline-block" role="presentation"><path
                            stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"></path></svg><span
                        class="text-white dark:text-gray-800 ml-2 font-bold">DTO</span></dropdowntrigger></span></div>
    </div>
</div>
```

And this is the html that works using nova 4.27.14 and nova-calendar 2.1.2 on my other project:
```
<div id="nc-control">
    <div class="left-items"><a href="#" class="button hover:bg-gray-100 dark:hover:bg-gray-700" title="Alt + ←">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7m8 14l-7-7 7-7"></path>
            </svg>
        </a><a href="#" class="button hover:bg-gray-100 dark:hover:bg-gray-700" title="Alt + H">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <circle cx="12" cy="12" r="2" fill="currentColor"></circle>
            </svg>
        </a><a href="#" class="button hover:bg-gray-100 dark:hover:bg-gray-700" title="Alt + →">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                 stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7"></path>
            </svg>
        </a>
        <div class="flex h-9 hover:bg-gray-100 dark:hover:bg-gray-700 rounded" dusk="month-picker">
            <button aria-expanded="true"
                    class="rounded active:outline-none active:ring focus:outline-none focus:ring focus:ring-primary-200 dark:focus:ring-gray-600"
                    type="button">
                <div class="toolbar-button flex items-center cursor-pointer select-none toolbar-button px-2"
                     style="padding-left: 0px;">
                    <svg class="flex-shrink-0 ml-2" xmlns="http://www.w3.org/2000/svg" width="10" height="6"
                         viewBox="0 0 10 6">
                        <path class="fill-current"
                              d="M8.292893.292893c.390525-.390524 1.023689-.390524 1.414214 0 .390524.390525.390524 1.023689 0 1.414214l-4 4c-.390525.390524-1.023689.390524-1.414214 0l-4-4c-.390524-.390525-.390524-1.023689 0-1.414214.390525-.390524 1.023689-.390524 1.414214 0L5 3.585786 8.292893.292893z"></path>
                    </svg>
                </div>
            </button>
        </div>
        <h1 class="text-90 font-normal text-xl md:text-2xl noselect"><span>Aprile '23</span></h1></div>
    <div class="center-items"></div>
    <div class="right-items">
        <div class="flex h-9 hover:bg-gray-100 dark:hover:bg-gray-700 rounded" dusk="filter-selector">
            <button aria-expanded="false"
                    class="rounded active:outline-none active:ring focus:outline-none focus:ring focus:ring-primary-200 dark:focus:ring-gray-600"
                    type="button">
                <div class="toolbar-button flex items-center cursor-pointer select-none toolbar-button px-2">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                         width="24" height="24" class="inline-block" role="presentation">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                              d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"></path>
                    </svg><!---->
                    <svg class="flex-shrink-0 ml-2" xmlns="http://www.w3.org/2000/svg" width="10" height="6"
                         viewBox="0 0 10 6">
                        <path class="fill-current"
                              d="M8.292893.292893c.390525-.390524 1.023689-.390524 1.414214 0 .390524.390525.390524 1.023689 0 1.414214l-4 4c-.390525.390524-1.023689.390524-1.414214 0l-4-4c-.390524-.390525-.390524-1.023689 0-1.414214.390525-.390524 1.023689-.390524 1.414214 0L5 3.585786 8.292893.292893z"></path>
                    </svg>
                </div>
            </button>
        </div>
    </div>
</div>
```

As you can see they are really different. SVG is missing in the first one and there is this strange tag dropdowntrigger.

I resolved with custom css but if it returns like the second html sent, it would be better.

dropdowntrigger, dropdowntrigger span {
  color: #64748B!important;
}
div[dusk="month-picker"] dropdowntrigger.toolbar-button {
  background-image: url('/arrow-down.svg');
  background-repeat: no-repeat;
  background-position: center center;
  cursor: pointer;
  padding-right: 30px;
}

Thank you!

**Comment by wdelfuego** [comment] 2024-02-27 13:50
I'll look into this further when I can, but first, did you publish Nova's assets after updating?

**Comment by Eli-Pez** [comment] 2024-02-27 13:56
yes i did
php artisan nova:publish
php artisan view:clear

**Comment by wdelfuego** [comment] 2024-02-27 14:07
Would you be able to provide a testing repo that demonstrates the issue using a clean install of just Nova and this calendar tool?

**Comment by wdelfuego** [comment] 2024-04-18 16:41
Closing due to lack of reproducibility.

Feel free to update this issue if you can reproduce the issue in a clean repo and I'll look into it.

**Closed by wdelfuego** 2024-04-18 16:41 UTC
Labels: question
