### ISSUE TITLE
   ERROR  There are no commands defined in the "nova-calendar" namespace.  

### ISSUE THREAD

**Issue by BeiAduo** [wdelfuego/nova-calendar#57] opened 2023-05-13 03:28 UTC
php artisan nova-calendar:create-default-calendar-data-provider
   ERROR  There are no commands defined in the "nova-calendar" namespace.

**Comment by wdelfuego** [comment] 2023-05-15 10:42
I can't reproduce this error, are you sure the package is correctly installed in your project?

To check, what is the output of running `composer show wdelfuego/nova-calendar` in your project directory?

**Comment by wdelfuego** [comment] 2023-05-26 13:42
Can't reproduce; closing due to lack of info

**Closed by wdelfuego** 2023-05-26 13:42 UTC
Labels: question, in progress
